FPS = 60
SC_WIDTH = 600
SC_HEIGHT = 800
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

PLAYER_FILE_NAME = "images\\player.png"
PLAYER_MAX_HP = 100
PLAYER_SPEED = 10

LASER_FILE_NAME = "images\\laser.png"
LASER_SPEEDY = 8

GAME_OVER_FILENAME = "images\\game_over.png"

FIRE_DELAY = 200

BONUS_SPEED = 1
BONUC_CHANCE = 50
PILL_HP = 25

SHIELD_FILENAME = "images\\shield.png"
SHIELD_RUNTIME = 10000
SHIELD_INACTIVE_POS = (100, 1000)

THREE_LASER_RUNTIME = 15000

EXPLOSION_FILENAME_PREFIX = "images\\regularExplosion0"
EXPLOSION_FILENAME_POSTFIX = ".png"






